= Cities
== Targos
Size: big
Type: main city in the regions
Main Inn: Northlook Inn
Speaker:

== Brynn Chander
Size: little
Type:
Main Inn:
Speaker:

== Targos
Size: Medium
Type: Fishing village
Main Inn:
Speaker: Maxildanarr

== Termalaine
Size: Medium
Type: one of the nicest towns in Icewindale. Forest is north, Maer Dualdon is West.
Main Inn: The Blue Clam
Speaker: Orus Mastiu
Yeti skins have been left for tanning in this city.

== Lonelywood
Holds the safe house of the party
Friends with the speaker
Speaker: Nimsy Huddle

== Black Cabin

== The Ramshackle
Safe house to the party

== Bremen
Size: Really small, 150 people
Type:
Speaker:
Inn: Burried Treasures
The city is disconnected from the rest of the 10 towns
Inn tender: Cara Mulphoon, super nice
Town flag: The gold circle represents treasures that are revealed during floods. Blue band is the river, the blue triangle is the lake

== Revel's End
Up North.This is where bad people go. They stay a long time. It is a prison.

== Caer Konig
Closest town to Kelvin's Cairn. 
A completely ruined castle.
The lake is frozen.
Speaker: Trovus

== Caer Dineval
A castle. Famous for its fortifications, atop cliffs. At the bottom is a port. The castle is inhabited, in good conditions.
Speaker: Crannoc Siever
Lanthis: scribe to the speaker

== Eastheaven
Life is good there, suposedly. The speaker is Waylen.
This is a Big city, along the lake Dinneshere. There are a lot of houses. The town is open to the Tundra, and feels like a city. This is a metropolis to Goliaths.

There is no gate to enter.

Brown: East
Blue: lake Dinnesheere
Tower: city

Thieves seem to be all over the place.

The captain of the militia is Captain Arlaggath

The Inn is the White Lady


