= The Far North Campaign
:atoc:

== Characters
Alli: Larme
Ray: Lordock
Rick: J.Peg
Chris: Lucius
Elliot: Eggo
Aleca: Tonith
Vincent: Harry
Martin: Ravina

== Creatures
Arveiaturace: the white worm, ancient white dragon. Eats dear, bears, etc. Does not attack people.

== Cities
=== Targos
Size: big
Type: main city in the regions
Main Inn: Northlook Inn
Speaker:

== Brynn Chander
Size: little
Type:
Main Inn:
Speaker:

== Targos
Size: Medium
Type: Fishing village
Main Inn:
Speaker: Maxildanarr

== Termalaine
Size: Medium
Type: one of the nicest towns in Icewindale. Forest is north, Maer Dualdon is West.
Main Inn: The Blue Clam
Speaker: Orus Mastiu
Yeti skins have been left for tanning in this city

== Quests
=== Fishing the Plesiasaurus
Thally: Academic. In for Lucius.

[%hardbreaks]
*_Ode to Harry Putter and the vicious fishes_*
_Well if a lake is a tiny sea,_
_N a shark is an angry dolphin,_
_Let me bring you to the north,_
_To the icy waters of Maer Dauldon._
_This is a story of a Plesisaurous,_
_Do you think he saw us?_
_N a group who was its bane,_
_Let me spit their names:_
_We got Torinth, Ravina, Larme, Lordock._
_Jean, Pur, lucious n Eggo,_
_All deserve praise, but one above them let's go_
_Chorus_
_When I say Harry you say Putter,_
_Harry (Putter) Harry (Putter) x3_
_He took of all his clothes,_
_N jumped in that tiny sea._
_He was vicious with dem fishes,_
_He was vicious with dem fishes,_
_With his rope he was malicious,_
_We dragged it back n made some delicious dishes._
_Chorus X 3_
[%hardbreaks/]

=== Saving private Garett
Go to Kelvin's cairn and save Garett
Keygan: dwarf, owner of dogs and sledges
Boy: Leading dog
Garett: the climber who fell
Mokingo Growling Bear Akannathi: goliath. Dead, murdered by a yeti
Perilou Fishfinger: hafling, saved from the yeti
Astrix: Tiefling. Dead, frozen, solid

The party tells Thally about the dragon. She seems interested. The Yeti skins are left for preparation.

=== The Mine
The mission has been given by Orus.
Clear the mine for 80 gold and a free diner. Half an hour north of the village.
Only hill with trees

==== Level 1
===== Entrance
Signs with "Kobolts only"
The party picks tools
Kobolt tracks at the entrance of the mine
Harry engraves walls as far as the party moves
Lordock Draws a map

===== Working room
Rocks on the floor, picks, hammers
People did not clean up after they left
Place where they extract the gems from the rock, trimming the rocks before taking them out
Larm finds a figurine of dog, with eyers made of termalaine

===== Shaft room
Big water fall cascades down in a shaft, down to the underdark
Walkway made of wooden planks
Super noisy, we need to shout to communicate
Larm: goes first
Tonith: Looks for places to attach a rope, but finds nothing. It is just a walkway
Eggo: braves it
Harry: drops a rock to estimate the depth. The rocks rolls down, but he cant hear it touch the ground because of the noise.
There is a corridor at the end of the map, with a smaller room

===== Pulley room
Pulley system, with a thick rope attached to the ceiling. A basket can hold up 3 people. 3 alcoves with equipment

===== Source room
Ravina investigating alcoves
3 Big rats are at the source of an underwater river. Harry runs at them and slices one of them.
There are gems in the room, but it would need time and tools to pick.

The water is warmer near the source. Harry ties a rope to himself and tries to go there. But the current is too strong, and Harry is too weak. J Peg does not feel Harry requesting help on the other end of the rope. Nobody actually does. Tonith spots him and tells the others.
Lordock is touching Eggo with _Strength of the Bull_. Eggo gets super strong. Harry is grasping for hair and flailing with his arms, and falls into the darkness. The rope goes tight. Ravina is casting _Destroy Water_, which allows Harry to get 1 second free of water.

Eggo pulls pulls while Harry holds his breath. He takes him out of the water, and Harry is finally safe. He dries himself with an apron, gets dressed again and evenutally warms up.

The party continues: "To the shaft!", and eventually to the pulley room.

===== Pulley room
Ravina jumps in the basket and starts turning the crank. Ravina goes down slowly and reaches another level. 

Larme is cranking back up, jumpts in the basket, and goes down. Do do the others.

==== Level 2
===== Small cave
Ravina gets there first. This is a small cave where two tunnels lead in opposite directions.

Larme joins, and then Lordock. And evenutally everybody. The party takes the tunnel going North.

===== Bigger cave
It is a bigger cave, with a ridge. The upper part of the room glooms with gems. Lorkock continues drawing the map. The shaft is visible in the West. Harry tries to chip gems from the wall, with pain. Larme explores the southern end of the corridor.

the party leaves the room, and Harry stays behind for a bit.

Harry stops, and tries to walk back to the party. At some point, he looks up and see creatures on the ceiling. Just a few feet away. Those are grells... Fleshy brains, with a beak, and tentacules spreading 10 feet away. Harry tucks his head in his shoulder, and tries to slowly retreats, keeping stealth.

But the grell starts to crawl on the ceiling and follows Harry. And then a tentacule tries to reach out to Harry. He freezes, dodging, ready to attack if there is another attempt.

The grell attacks again, and hits. Harry responds with the _attack of the pissed off squirrel_, and hits twice. The fight continues. Tentacle, tentacle, beak, sandwedge, tentacle, tentacle, etc. Harry got a real big fail once. Lordock joins, and nails the grell with a _Guiding bolt_.

===== New chamber
Eggo and Lordock gest in first. They see figures moving at the end of their torch lights. They are kobolts: reptilian faced, pathetic versions of a dragon.

Lucius tries to calm the situation, but the Kobolts grb their javelins, and say something. He holds hands up, but they keep running. Lordock draws an arrow, but misses. The rest of the party engages with them. It is a bath of blood and magic. Suddenly, a third kobolt appears and joins the battle. They are defeated, and the head of the party continues while a handful of them go back to support Harry.



