= The Far North Campaign
:atoc:

== Characters
Alli: Larme
Ray: Lordock
Rick: J.Peg
Chris: Lucius
Elliot: Eggo
Aleca: Tonith
Vincent: Harry
Martin: Ravina

== Creatures
Arveiaturace: the white worm, ancient white dragon. Eats dear, bears, etc. Does not attack people.

== Cities
=== Targos
Size: big
Type: main city in the regions
Main Inn: Northlook Inn
Speaker:

== Brynn Chander
Size: little
Type:
Main Inn:
Speaker:

== Targos
Size: Medium
Type: Fishing village
Main Inn:
Speaker: Maxildanarr

== Termalaine
Size: Medium
Type: one of the nicest towns in Icewindale. Forest is north, Maer Dualdon is West.
Main Inn: The Blue Clam
Speaker: Orus Mastiu
Yeti skins have been left for tanning in this city

== Quests
=== Fishing the Plesiasaurus
Thally: Academic. In for Lucius.

[%hardbreaks]
*Ode to Harry Putter and the vicious fishes*
__Well if a lake is a tiny sea,
N a shark is an angry dolphin,
Let me bring you to the north,
To the icy waters of Maer Dauldon.
This is a story of a Plesisaurous,
Do you think he saw us?
N a group who was its bane,
Let me spit their names:
We got Torinth, Ravina, Larme, Lordock.
Jean, Pur, lucious n Eggo,
All deserve praise, but one above them let's go!

Chorus
When I say Harry you say Putter,
Harry (Putter) Harry (Putter) X3

If a dwarf is a tiny man,
Let's judge him by his deeds.
He took of all his clothes,
N jumped in that tiny sea.
He was vicious with dem fishes, 
With his rope he was malicious, 
We dragged it back n made some delicious dishes.

Chorus X 3__
[%hardbreaks/]

=== Saving private Garett
Go to Kelvin's cairn and save Garett
Keygan: dwarf, owner of dogs and sledges
Boy: Leading dog
Garett: the climber who fell
Mokingo Growling Bear Akannathi: goliath. Dead, murdered by a yeti
Perilou Fishfinger: hafling, saved from the yeti
Astrix: Tiefling. Dead, frozen, solid

The party tells Thally about the dragon. She seems interested. The Yeti skins are left for preparation.

=== The Mine
The mission has been given by Orus.
Clear the mine for 80 gold and a free diner. Half an hour north of the village.
Only hill with trees

==== Entrance
Signs with "Kobolts only"
The party picks tools
Kobolt tracks at the entrance of the mine
Harry engraves walls as far as the party moves
Lordock Draws a map

==== Working room
Rocks on the floor, picks, hammers
People did not clean up after they left
Place where they extract the gems from the rock, trimming the rocks before taking them out
Larm finds a figurine of dog, with eyers made of termalaine

==== Shaft room
Big water fall cascades down in a shaft, down to the underdark
Walkway made of wooden planks
Super noisy, we need to shout to communicate
Larm: goes first
Tonith: Looks for places to attach a rope, but finds nothing. It is just a walkway
Eggo: braves it
Harry: drops a rock to estimate the depth. The rocks rolls down, but he cant hear it touch the ground because of the noise.
There is a corridor at the end of the map, with a smaller room

==== Pulley room
Pulley system, with a thick rope attached to the ceiling. A basket can hold up 3 people. 3 alcoves with equipment

==== Source room
Ravina investigating alcoves
3 Big rats are at the source of an underwater river.
Harry runs at them and slices a rat.
There are gems in the room, but it would need time and tools to pick.
The water is warmer near the source.
Harry ties a rope to himself and tries to go to the source. Current is too strong, Harry is too weak. J Peg does not feel Harry requesting help on the other end of the rope. Nobody actually does. Tonith spots him and tells the others.
Lordock is touching Eggo with _Strength of the Bull_. Eggo gets super strong.














