= The Far North Campaign
:atoc:

== Characters
Alli: Larme
Ray: Lordock
Rick: J.Peg
Chris: Lucius
Elliot: Eggo
Aleca: Tonith
Vincent: Harry
Martin: Ravina

== Creatures
Arveiaturace: the white worm, ancient white dragon. Eats dear, bears, etc. Does not attack people.

== Cities
=== Targos
Size: big
Type: main city in the regions
Main Inn: Northlook Inn
Speaker:

== Brynn Chander
Size: little
Type:
Main Inn:
Speaker:

== Targos
Size: Medium
Type: Fishing village
Main Inn:
Speaker: Maxildanarr

== Termalaine
Size: Medium
Type: one of the nicest towns in Icewindale. Forest is north, Maer Dualdon is West.
Main Inn: The Blue Clam
Speaker: Orus Mastiu
Yeti skins have been left for tanning in this city

== Quests
=== Fishing the Plesiasaurus
Thally: Academic. In for Lucius.

[%hardbreaks]
*_Ode to Harry Putter and the vicious fishes_*
_Well if a lake is a tiny sea,_
_N a shark is an angry dolphin,_
_Let me bring you to the north,_
_To the icy waters of Maer Dauldon._
_This is a story of a Plesisaurous,_
_Do you think he saw us?_
_N a group who was its bane,_
_Let me spit their names:_
_We got Torinth, Ravina, Larme, Lordock._
_Jean, Pur, lucious n Eggo,_
_All deserve praise, but one above them let's go_
_Chorus_
_When I say Harry you say Putter,_
_Harry (Putter) Harry (Putter) x3_
_He took of all his clothes,_
_N jumped in that tiny sea._
_He was vicious with dem fishes,_
_He was vicious with dem fishes,_
_With his rope he was malicious,_
_We dragged it back n made some delicious dishes._
_Chorus X 3_
[%hardbreaks/]

=== Saving private Garett
Go to Kelvin's cairn and save Garett
Keygan: dwarf, owner of dogs and sledges
Boy: Leading dog
Garett: the climber who fell
Mokingo Growling Bear Akannathi: goliath. Dead, murdered by a yeti
Perilou Fishfinger: hafling, saved from the yeti
Astrix: Tiefling. Dead, frozen, solid

The party tells Thally about the dragon. She seems interested. The Yeti skins are left for preparation.

=== The Mine
The mission has been given by Orus.
Clear the mine for 80 gold and a free diner. Half an hour north of the village.
Only hill with trees

==== Level 1
===== Entrance
Signs with "Kobolts only"
The party picks tools
Kobolt tracks at the entrance of the mine
Harry engraves walls as far as the party moves
Lordock Draws a map

===== Working room
Rocks on the floor, picks, hammers
People did not clean up after they left
Place where they extract the gems from the rock, trimming the rocks before taking them out
Larm finds a figurine of dog, with eyers made of termalaine

===== Shaft room
Big water fall cascades down in a shaft, down to the underdark
Walkway made of wooden planks
Super noisy, we need to shout to communicate
Larm: goes first
Tonith: Looks for places to attach a rope, but finds nothing. It is just a walkway
Eggo: braves it
Harry: drops a rock to estimate the depth. The rocks rolls down, but he cant hear it touch the ground because of the noise.
There is a corridor at the end of the map, with a smaller room

===== Pulley room
Pulley system, with a thick rope attached to the ceiling. A basket can hold up 3 people. 3 alcoves with equipment

===== Source room
Ravina investigating alcoves
3 Big rats are at the source of an underwater river. Harry runs at them and slices one of them.
There are gems in the room, but it would need time and tools to pick.

The water is warmer near the source. Harry ties a rope to himself and tries to go there. But the current is too strong, and Harry is too weak. J Peg does not feel Harry requesting help on the other end of the rope. Nobody actually does. Tonith spots him and tells the others.
Lordock is touching Eggo with _Strength of the Bull_. Eggo gets super strong. Harry is grasping for hair and flailing with his arms, and falls into the darkness. The rope goes tight. Ravina is casting _Destroy Water_, which allows Harry to get 1 second free of water.

Eggo pulls pulls while Harry holds his breath. He takes him out of the water, and Harry is finally safe. He dries himself with an apron, gets dressed again and evenutally warms up.

The party continues: "To the shaft!", and eventually to the pulley room.

===== Pulley room
Ravina jumps in the basket and starts turning the crank. Ravina goes down slowly and reaches another level. 

Larme is cranking back up, jumpts in the basket, and goes down. Do do the others.

==== Level 2
===== Small cave
Ravina gets there first. This is a small cave where two tunnels lead in opposite directions.

Larme joins, and then Lordock. And evenutally everybody. The party takes the tunnel going North.

===== Bigger cave
It is a bigger cave, with a ridge. The upper part of the room glooms with gems. Lorkock continues drawing the map. The shaft is visible in the West. Harry tries to chip gems from the wall, with pain. Larme explores the southern end of the corridor.

the party leaves the room, and Harry stays behind for a bit.

Harry stops, and tries to walk back to the party. At some point, he looks up and see creatures on the ceiling. Just a few feet away. Those are grells... Fleshy brains, with a beak, and tentacules spreading 10 feet away. Harry tucks his head in his shoulder, and tries to slowly retreats, keeping stealth.

But the grell starts to crawl on the ceiling and follows Harry. And then a tentacule tries to reach out to Harry. He freezes, dodging, ready to attack if there is another attempt.

The grell attacks again, and hits. Harry responds with the _attack of the pissed off squirrel_, and hits twice. The fight continues. Tentacle, tentacle, beak, sandwedge, tentacle, tentacle, etc. Harry got a real big fail once. Lordock joins, and nails the grell with a _Guiding bolt_.

As Jpeg meets up, he takes the beak away.

===== New chamber
Eggo and Lordock gest in first. They see figures moving at the end of their torch lights. They are kobolts: reptilian faced, pathetic versions of a dragon.

Lucius tries to calm the situation, but the Kobolts grb their javelins, and say something. He holds hands up, but they keep running. Lordock draws an arrow, but misses. The rest of the party engages with them. It is a bath of blood and magic. Suddenly, a third kobolt appears and joins the battle. They are defeated, and the head of the party continues while a handful of them go back to support Harry.

==== Level 3
===== Shaft and corridor
The tunnel continues turning down under, to the shaft. A rope is tied in the middle, with a basket under it. Three liveing kobolts are hanging from the scaffolding above the party's head. They are sawing wood, cutting rope to sabotaging the platform.

Three mage hands raise up, with daggers in them. They float up twenty feet away to the darkness, approaching the kobolts. The hands start cutting the ropes. it takes two a re three cuts, and the kobolts drop free. The scream and try to grab on ropes and everything that they find. Two of them disappear in the darkness, one miracously manages to catch a peg in the scaffolding and escapes the fall. Eggo mocks him, He finally lets go and falls to the darkness.

Harry drops a torch in the shaft, trying to reveal other levels in the mine. But nothing is to be revealed.

In the tunnel, three fake kobolts made of cloth of wood, one of them carrying dragon wing. They say in common "we mean no harm don't hurt us". Eggo tries to charm them: "we are willing to hear what you say, but you have to tell us what is really going on here, and why are you here".

The one with the wings introduces himself. His name is Trex, and does not want to be hurt.

Eggo: "You seem to be aggressive. What happen to the people working here? This is not your mine. Are you a Kobolt?"

Trex: "Of course we are. Here are my body guards. Volt and Zurk"
`
Ravina: "Where are the miners?"

Trex: "They all went back to town. We are looking for whelter from the yetis from Kelvin's Cairn"

Lucius: "The Yetis are dead. Drop weapons and go back"

Trex: "We mean no harm. People just left. We just want to stay out of the winter and the yetis"

Ravina cats _Detect magic_. Trex glows magic.

Harry: "Did yuo write the sign at the entrance of the mine"

Trex: "yes we did, we are just trying to stay safe. We can work, we are strong, we just want to work."

Eggo: "we just saw kobolts trying to booby trap the scaffolding. What you say is fake"

Trex: "Fake?? We have draconic blood"

Larme speaks in draconic, but Trex does not answer.

Tonith: "How many kobolts are you?"

Trerx "Around a dozen"

Lucius "Yeah, a few less now"

Tonis approaches and go shake hands with Trex.

Trex: "This is a good development. Take us to Termalaine, and we will tell them we will work for them, out of the cold. Help us go back to Termalaine. I am so glad we can talk about this"

Tonith casts _Identify Magic_, and understand the Kobolt is possessed. Lordock steps forward, lift up his shield and channels divinity. He turns undead, but nothing happens.

Harry: "Why are you wearing wings?"

Trex "Those are my wings"

JPeg: "What's in the backpack?"

Trex does not answer.

Lordock casts _Sacred Flame_ on the satchel. A flame burts from his shiel between Tonith and Larme, zeroing in on the satchel. It goes up in flame and starts burning. As it burns, Trex yells "No, no, no" louder and louder. The two kobolts at the back steps back. It smells herb and strange odors. It starts to burn him while he burns, and something spectral goes out of him. The kobolt drops to the ground. A spectral ghost stands in front, but disbands with the satchel.

The two other kobolts step back.

Larme: "we will tie you up, and release you when we come back. But you cannot leave this cave"

The two kobolts: "no tie up, afraid of yetis, many yetis"

Larme: "we can tie you up, or kill you"

Harry tries to grapple one of them, to help tie them up. He asks Larme to tie him up. Same for the second one. They struggle against their struggle.

The party moves back to the basket with the kobolts, and drop them in it to assess its resistance. Eggo pulls the rope, and it seems resistant enough. Eggo goes in the bucket first. The rest of the party does the same and reaches the other side.


===== Small chamber
This is a weird room with a Fossilised skull. Lordock and Harry investigate it.

===== Bigger chamber
Tonith meets 4 injured kobolts. Tonith and Eggo puts them to sleep, one of them even dies. They tie them up quickly before the awake.










