= The Far North Campaign
:atoc:





== Black Cabin

== Quests
=== Fishing the Plesiasaurus
Thally: Academic. In for Lucius.

[%hardbreaks]
*_Ode to Harry Putter and the vicious fishes_*
_Well if a lake is a tiny sea,_
_N a shark is an angry dolphin,_
_Let me bring you to the north,_
_To the icy waters of Maer Dauldon._
_This is a story of a Plesisaurous,_
_Do you think he saw us?_
_N a group who was its bane,_
_Let me spit their names:_
_We got Torinth, Ravina, Larme, Lordock._
_Jean, Pur, lucious n Eggo,_
_All deserve praise, but one above them let's go_
_Chorus_
_When I say Harry you say Putter,_
_Harry (Putter) Harry (Putter) x3_
_He took of all his clothes,_
_N jumped in that tiny sea._
_He was vicious with dem fishes,_
_He was vicious with dem fishes,_
_With his rope he was malicious,_
_We dragged it back n made some delicious dishes._
_Chorus X 3_
[%hardbreaks/]

=== Saving private Garett
Go to Kelvin's cairn and save Garett
Keygan: dwarf, owner of dogs and sledges
Boy: Leading dog
Garett: the climber who fell
Mokingo Growling Bear Akannathi: goliath. Dead, murdered by a yeti
Perilou Fishfinger: hafling, saved from the yeti
Astrix: Tiefling. Dead, frozen, solid

The party tells Thally about the dragon. She seems interested. The Yeti skins are left for preparation.

=== The Mine
The mission has been given by Orus.
Clear the mine for 80 gold and a free diner. Half an hour north of the village.
Only hill with trees

==== Level 1
===== Entrance
Signs with "Kobolts only"
The party picks tools
Kobolt tracks at the entrance of the mine
Harry engraves walls as far as the party moves
Lordock Draws a map

===== Working room
Rocks on the floor, picks, hammers
People did not clean up after they left
Place where they extract the gems from the rock, trimming the rocks before taking them out
Larm finds a figurine of dog, with eyers made of termalaine

===== Shaft room
Big water fall cascades down in a shaft, down to the underdark
Walkway made of wooden planks
Super noisy, we need to shout to communicate
Larm: goes first
Tonith: Looks for places to attach a rope, but finds nothing. It is just a walkway
Eggo: braves it
Harry: drops a rock to estimate the depth. The rocks rolls down, but he cant hear it touch the ground because of the noise.
There is a corridor at the end of the map, with a smaller room

===== Pulley room
Pulley system, with a thick rope attached to the ceiling. A basket can hold up 3 people. 3 alcoves with equipment

===== Source room
Ravina investigating alcoves
3 Big rats are at the source of an underwater river. Harry runs at them and slices one of them.
There are gems in the room, but it would need time and tools to pick.

The water is warmer near the source. Harry ties a rope to himself and tries to go there. But the current is too strong, and Harry is too weak. J Peg does not feel Harry requesting help on the other end of the rope. Nobody actually does. Tonith spots him and tells the others.
Lordock is touching Eggo with _Strength of the Bull_. Eggo gets super strong. Harry is grasping for hair and flailing with his arms, and falls into the darkness. The rope goes tight. Ravina is casting _Destroy Water_, which allows Harry to get 1 second free of water.

Eggo pulls pulls while Harry holds his breath. He takes him out of the water, and Harry is finally safe. He dries himself with an apron, gets dressed again and evenutally warms up.

The party continues: "To the shaft!", and eventually to the pulley room.

===== Pulley room
Ravina jumps in the basket and starts turning the crank. Ravina goes down slowly and reaches another level. 

Larme is cranking back up, jumpts in the basket, and goes down. Do do the others.

==== Level 2
===== Small cave
Ravina gets there first. This is a small cave where two tunnels lead in opposite directions.

Larme joins, and then Lordock. And evenutally everybody. The party takes the tunnel going North.

===== Bigger cave
It is a bigger cave, with a ridge. The upper part of the room glooms with gems. Lorkock continues drawing the map. The shaft is visible in the West. Harry tries to chip gems from the wall, with pain. Larme explores the southern end of the corridor.

the party leaves the room, and Harry stays behind for a bit.

Harry stops, and tries to walk back to the party. At some point, he looks up and see creatures on the ceiling. Just a few feet away. Those are grells... Fleshy brains, with a beak, and tentacules spreading 10 feet away. Harry tucks his head in his shoulder, and tries to slowly retreats, keeping stealth.

But the grell starts to crawl on the ceiling and follows Harry. And then a tentacule tries to reach out to Harry. He freezes, dodging, ready to attack if there is another attempt.

The grell attacks again, and hits. Harry responds with the _attack of the pissed off squirrel_, and hits twice. The fight continues. Tentacle, tentacle, beak, sandwedge, tentacle, tentacle, etc. Harry got a real big fail once. Lordock joins, and nails the grell with a _Guiding bolt_.

As Jpeg meets up, he takes the beak away.

===== New chamber
Eggo and Lordock gest in first. They see figures moving at the end of their torch lights. They are kobolts: reptilian faced, pathetic versions of a dragon.

Lucius tries to calm the situation, but the Kobolts grb their javelins, and say something. He holds hands up, but they keep running. Lordock draws an arrow, but misses. The rest of the party engages with them. It is a bath of blood and magic. Suddenly, a third kobolt appears and joins the battle. They are defeated, and the head of the party continues while a handful of them go back to support Harry.

==== Level 3
===== Shaft and corridor
The tunnel continues turning down under, to the shaft. A rope is tied in the middle, with a basket under it. Three liveing kobolts are hanging from the scaffolding above the party's head. They are sawing wood, cutting rope to sabotaging the platform.

Three mage hands raise up, with daggers in them. They float up twenty feet away to the darkness, approaching the kobolts. The hands start cutting the ropes. it takes two a re three cuts, and the kobolts drop free. The scream and try to grab on ropes and everything that they find. Two of them disappear in the darkness, one miracously manages to catch a peg in the scaffolding and escapes the fall. Eggo mocks him, He finally lets go and falls to the darkness.

Harry drops a torch in the shaft, trying to reveal other levels in the mine. But nothing is to be revealed.

In the tunnel, three fake kobolts made of cloth of wood, one of them carrying dragon wing. They say in common "we mean no harm don't hurt us". Eggo tries to charm them: "we are willing to hear what you say, but you have to tell us what is really going on here, and why are you here".

The one with the wings introduces himself. His name is Trex, and does not want to be hurt.

Eggo: "You seem to be aggressive. What happen to the people working here? This is not your mine. Are you a Kobolt?"

Trex: "Of course we are. Here are my body guards. Volt and Zurk"
`
Ravina: "Where are the miners?"

Trex: "They all went back to town. We are looking for whelter from the yetis from Kelvin's Cairn"

Lucius: "The Yetis are dead. Drop weapons and go back"

Trex: "We mean no harm. People just left. We just want to stay out of the winter and the yetis"

Ravina cats _Detect magic_. Trex glows magic.

Harry: "Did yuo write the sign at the entrance of the mine"

Trex: "yes we did, we are just trying to stay safe. We can work, we are strong, we just want to work."

Eggo: "we just saw kobolts trying to booby trap the scaffolding. What you say is fake"

Trex: "Fake?? We have draconic blood"

Larme speaks in draconic, but Trex does not answer.

Tonith: "How many kobolts are you?"

Trerx "Around a dozen"

Lucius "Yeah, a few less now"

Tonis approaches and go shake hands with Trex.

Trex: "This is a good development. Take us to Termalaine, and we will tell them we will work for them, out of the cold. Help us go back to Termalaine. I am so glad we can talk about this"

Tonith casts _Identify Magic_, and understand the Kobolt is possessed. Lordock steps forward, lift up his shield and channels divinity. He turns undead, but nothing happens.

Harry: "Why are you wearing wings?"

Trex "Those are my wings"

JPeg: "What's in the backpack?"

Trex does not answer.

Lordock casts _Sacred Flame_ on the satchel. A flame burts from his shiel between Tonith and Larme, zeroing in on the satchel. It goes up in flame and starts burning. As it burns, Trex yells "No, no, no" louder and louder. The two kobolts at the back steps back. It smells herb and strange odors. It starts to burn him while he burns, and something spectral goes out of him. The kobolt drops to the ground. A spectral ghost stands in front, but disbands with the satchel.

The two other kobolts step back.

Larme: "we will tie you up, and release you when we come back. But you cannot leave this cave"

The two kobolts: "no tie up, afraid of yetis, many yetis"

Larme: "we can tie you up, or kill you"

Harry tries to grapple one of them, to help tie them up. He asks Larme to tie him up. Same for the second one. They struggle against their struggle.

The party moves back to the basket with the kobolts, and drop them in it to assess its resistance. Eggo pulls the rope, and it seems resistant enough. Eggo goes in the bucket first. The rest of the party does the same and reaches the other side.


===== Small chamber
This is a weird room with a Fossilised skull. Lordock and Harry investigate it. It has larger than normal eye sockets. There are no nose. And small holes where there are supposed to be teeth.

Lordock looks for magic. He recognizes the skull when he was learning about wizards. This is the skull of a _Mine Flayer_: "It is floating eye ball of terror, an intelligent eye ball that floats and would kill us all". Magic is coming the skull cavity, from a shard.

Tonith joins to _Identify Magic_. It is a Cristal Shard: uncommon cristal that requires atunement. The _Psi Cristal_ grants telepathy powers to the owner of the cristal. Tonith gives the cristal to Lordock, under protection of his knowledge and wisdom.

Harry begins extracting the skull, but it tumbles to the ground into pieces.

===== Bigger chamber
Tonith meets 4 injured kobolts. Tonith and Eggo puts them to sleep, one of them even dies. They tie them up quickly before they awake.
The party goes back up, and meet Purrr there.

==== Back to Termalaine, and in the wood
The party met the guards of Brynn Chander, the inn keeper and Thally having a fight outside.
The officials from Brynn Chanber looking for Ravina: Ravina won the lotery for the sacrifice. Tonith stood and pissed the leader who sent the guards to arrest them.
In another part of the city, an army of guards are trying to capture everybody.

The party left ot hide in the forrest.

Thonis called out the law.

Thally is with the group, in the forrest. Everybody is 1 mile deep in the forrest. It is time to bivouac. Resting is still impossible because of the cold. There are stories about the danger in the wood. Large footprints that she collected support those stories.

Thonis atuned with the Psy Cristal, now purple. But Thonis now gets hallucinations...

The party decides to leave for Lonelywood.

It meets a white moose, that Thonis tries to get in touch with. The moose speaks back to Tonith: "There is a moose master who works for the Frost Maiden. There are larger forces at work. If we do not worship the Frost Maiden, you need to die". A harsh battle follows.

The party follows the track of the dead moose.

Telepathic beacon from the South.

Larme and Ravina leave the group, to lure teh guards afar from the group.

Tonith, JPEG and Harry follow the tracks.

==== Tracking the moose
Wolf in the distance. The group loses sense of direction. The forrest gets less dense. The track leads to a large row of white marble statues atop granit pillars. They depict thinned robbed figures. They are lifesized, faced away by the element. They have pointed ears: elves!

Harry tries to be cautious, and stands still trying to identify threat.

Tonith does not detect magic on the statues, but there is something magic about the place. Harry has a look at the stonework. It not dwarven, very old, elvish by construction and design.  This arrangement of stone is generally associated to funerals, cimetery, or a tomb.

The team takes a nap, before moving further in the structure.

Inside the building is a gnonom, showing phases of the moon.

The moose came from a door on the East, and the three adventurers go in, dropping a 10 feet step just behind the door.

There are bones everywhere. Foxes, goats, owls, wolf pups, a young bear are sharing space and hurdling together for warmth. Tonith telepathly coomunicate with Harry and JPEG:"they are servants of the Frost Maiden...".

A few of the animals ake up and notice the characters. They seem sedate and peacefull.

There are 3 marble statues. They are elves, facing east. They look like clerics or wizzards.

Harry picks up a baby wolf, and go down the stairs. A stone door is at the end of the stairs. There is an engraving, symbol of a half moon.

They try another corridor which ends at a mirror. There is a stone frame. It looks like the full moon.

Harry checks the third corridor, followed by Thonis. A door shows the other half moon.

They go back to the dial, and looks at the dials again. Tiny inscriptions are engraved:
- 9: "Unlock the tombs of the half moon"
- 12: "Gaze upon your own face and have 7 questions answered"
- 3: "Unlock the tombs of the half moon"

The party tries to redirect moon light to one of the dials, but it does not work.

Harry cannot take a piece of the cristal with the pick, and feels this is impossible to do.

On the other side of the strucutre, is a marble gazebo. the brasier is full of pine needles. It is not burning. JPEG lights the needles, nut nothing happens.

There are stairs a little more east, Tonith climbs them. At the top, a sarcophagei with 5 crystal pillars

Harry brushes the snow away from the sarcophagei, which reveals an encraving of a gazebo. Tonith sees a graving of a twig.

On each cristal colum:
- twig
- pine cone
- flame
- feather
- humanoid hand

The party splits to collect each element. A mage hand is conjured by Tonith in place of the humanoid hand. JPEG shove his hand in the fire.

A sliver flame arises and lights strongly. JPEG gets his hand out just in time.

Harry goes back to the sarcophagei. He slides the top off. There is a momie inside. It smells like pumpkin.

The momie says in Elvish: "Hello, I am Sahnar the moon, elf."

Harry: "What are yo doing here?"

Momie: "sleeping!"

Tonith: "Have you heard of the frost maiden? It has taken control of this land"

Momie: "that bitch! Ah! the moon dial"

Harry: "what is it for?"

Momie: "It tells you what phase of the moon it is. Is it still 357?"

Purr: "it is 300 years later. How can. You help?"

Tonith: "The frost maiden has commanded never ending winter"

Momie: "it sounds dangerous to kill the Frost Maiden"

Tonith: "Can you generate moon light?"

The momie creates a moon beam.

Tonith "we need your help to open the tombs"

The Momie lightens the dial with a moon beam. After a little chit chat, the party goes to the northern. The momie does not know about the animals.

==== Nothern sarcofagus
The tomb is a livinf corridor. Bedroll on the ground, rack of herbs, pots pans.

From behing the sarphagus, a druid jumps on top it. He shouts at Harry "10 towns will be destroyed! If not by my hand, but the Maidens!". This is Ravisin.

Purr tries to charm Ravisin, and then the battle starts. The party struggles, but finally takes the druid down.

The frost Maiden
Q1: the frost maiden is vulnerable to something but not fir
Q2: Lordocks mentor, Sarah is dead. Confirmed in the Big Black Cabin.
Q3: 



==== Black Cabin
Loenly wood: town speaker awarded us with a safe house
2 amulets:
- ?
- ?

Tonith touched an unfinished amulet. It started to glow.

The party is able to control wether within a 5 miles radius. With the summer star.

As the night passes by, a Coldnight Walker appears... Harry drops the puppy, and runs outside for a distraction. Every body draw weapons and the Walker is defeated.

At the same time, ice Mephits appear from the floor and attack Locius, Lordock, and Tonith from behind. 

The night goes by. In the morning, Lucius notices a body on a corner of the main room. The group investigates who this might be.

==== Back at the Ramshackle
Nimsy is invited to the house, and some of the story is shared.

Gossips from around the 10 towns:
- Wolves in Dougan's Hole. This is a rumor, though
- In East Haven, the person for the sacrifice escaped. The person was found murdered.
- Rumors about Giants
- People say that North west of Bremen, there is a pirate ship frozen in the ice
- Psi Crustal beacon to unknown location in the Spine of the world

==== Pirate boat
12 miles per day.

The group is leaving Lonelywood, heading north, turning around the Maer Dualdon, and continuing South to Bremen. The party reaches Bremen without too much issues in a few hours.

Rumors and news:
- she knows about Ravina and Larme. She saw the guards coming in by boat, and leave by boat. They left a day, looking all houses
- one castle intact "Caer Dineval", and one destroyed "Caer Konig". Her son went missing looking for the speaker. He did not find his way back until the following morning. He was severely frost bite. But he started changing his personality. One day she found him playing with a piece of black ice in his room. She took it away, but he became violent. Then 2 tieflings arrived and offered to take her son, who was mentally disturbed. They offered sanctuary. His son went willingly, telling her mom he would never return. The tieffling mentioned they would take him back to their castle (maybe one of the two castles). The name of the son is Huarwar.

In the morning, the party leaves. It continues across the day, heading towards an hypothetical direction that nothing can confirm. In the end of the day, icebergs are visible in the distance.

The groups settles for the night. Lordock will get up early to improve visibilty in the morning.















